routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard1');
});
Route::resource('etudiants', EtudiantController::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/index1', function () {
    return view('index1');
});
Route::get('/upload-file', [FileUpload::class, 'createForm']);

Route::post('/upload-file', [FileUpload::class, 'fileUpload'])->name('fileUpload');

app/Models/Etudiant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Etudiant extends Model
{
    use HasFactory;
    protected $fillable = [
        'nom',
        'prenom',
        'cin',
        'email',
       
    ];
}

app/Http/Controllers/EtudiantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Etudiant;
use Illuminate\Http\Request;

class EtudiantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $etudiants=Etudiant::paginate(5);
        return view('etudiants.index',compact('etudiants'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $etudiants=Etudiant::all();
        return view ('etudiants.create',compact('etudiants'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nom' => 'required',
            'prenom' =>'required',
            'cin' => 'required',
            'email' =>'required',
            
        ]);
    
        Etudiant::create($request->all());
     
        return redirect()->route('etudiants.index')
                        ->with('success','Etudiant créé avec succès.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Etudiant  $etudiant
     * @return \Illuminate\Http\Response
     */
    public function show(Etudiant $etudiant)
    {
        return view('etudiants.show',compact('etudiant'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Etudiant  $etudiant
     * @return \Illuminate\Http\Response
     */
    public function edit(Etudiant $etudiant)
    {
        $etudiants=Etudiant::all();
        return view ('etudiants.edit',compact('etudiant','etudiants'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Etudiant  $etudiant
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Etudiant $etudiant)
    {
        $request->validate([
            'nom'=>'required|string',
            'prenom'=>'required|string',
            'cin'=>'required|string',
            'email'=>'required|string',
            
        ]);
        $etudiant->update([
            'nom'=>$request->nom,
            'prenom'=>$request->prenom,
            'cin'=>$request->cin,
            'email'=>$request->email,
            


        ]);
        return redirect()->route('etudiants.index')->with('success','etudiant updated successfuly');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Etudiant  $etudiant
     * @return \Illuminate\Http\Response
     */
    public function destroy(Etudiant $etudiant)
    {
        $etudiant->delete();
        return redirect()->route('etudiants.index')->with('success','Etudiant a été supprimé ');
    }
}

resources/views/etudiants/create.blade.php
@extends('layouts1.master')
  
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ajouter étudiant</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('etudiants.index') }}">Liste étudiants</a></li>
              <li class="breadcrumb-item active">Etudiant</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">General</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>

   
<form action="{{ route('etudiants.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Nom</strong>
                <input type="text" name="nom" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Prénom</strong>
                <input type="text" name="prenom" class="form-control" placeholder="">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Cin</strong>
                <input type="text" name="cin" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Email</strong>
                <input type="text" name="email" class="form-control" placeholder="">
            </div>
        </div>
    </div>  
    
    
    <div class="row">
       
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Ajouter un étudiant</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/etudiants/edit.blade.php
@extends('layouts1.master')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Modifier étudiant</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('etudiants.index') }}">Liste étudiant</a></li>
              <li class="breadcrumb-item active">Etudiant</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">General</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <form action="{{ route('etudiants.update',$etudiant->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">Nom</label>
                <input type="text" id="inputName" name="name"  value="{{ $etudiant->nom }}" placeholder="name" class="form-control">
                @error('name')
                <div class="alert alert-danger">eb
                  {{$message}}
                </div>
                @enderror
            </div>
              <div class="form-group">
                <label for="inputDescription">Prénom</label>
                <input id="inputDescription" name="short_description"  value="{{ $etudiant->prenom }}" placeholder="short_description" class="form-control" rows="4">{{ $etudiant->short_description }}</textarea>
                @error('short_description')
                <div class="alert alert-danger">
                  {{$message}}
                </div>
                @enderror
            </div>

              <div class="form-group">
                <label for="inputClientCompany">CIN</label>
                <input type="text" id="inputClientCompany" name="price"   value="{{ $etudiant->cin }}" placeholder="price" class="form-control">
                @error('price')
                <div class="alert alert-danger">
                  {{$message}}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="inputClientCompany">Email</label>
                <input type="text" id="inputClientCompany" name="sale_price"   value="{{ $etudiant->email}}" placeholder="sale_price" class="form-control">
                @error('sale_price')
                <div class="alert alert-danger">
                  {{$message}}
                </div>
                @enderror
            </div>
           
           


            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <a href="#" class="btn btn-secondary">Cancel</a>
          <input type="submit" value="Modifier" class="btn btn-success float-right">
        </div>
      </div>
    </form>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/etudiants/index.blade.php
@extends('layouts1.master')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-start">
                <h2>Ajouter un étudiant</h2>
            </div>
            <div class="float-end">
                <a class="btn btn-outline-success" href="{{ route('etudiants.create') }}"> Créer un nouveau produit</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>CIN</th>
            <th>Email</th>
            
            <th width="280px">Action</th>
        </tr>
        @foreach ($etudiants as $etudiant)
        <tr>
           
            <td>{{ $etudiant->nom }}</td>
            <td>{{ $etudiant->prenom }}</td>
            <td>{{ $etudiant->cin }}</td>
            <td>{{ $etudiant->email }}</td>
            
            <td>
                <form action="{{ route('etudiants.destroy',$etudiant->nom) }}" method="POST">
   
                    <a class="btn btn-outline-primary" href="{{ route('etudiants.show',$etudiant->nom) }}">Montrer</a>
    
                    <a class="btn btn-outline-success" href="{{ route('etudiants.edit',$etudiant->prenom) }}">Éditer</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-outline-danger">Supprimer</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    <div class="d-flex justify-content-center pagination-lg">
    {!! $etudiants->links('pagination::bootstrap-4') !!}
      </div>
@endsection

resources/views/etudiants/show.blade.php
@extends('layouts1.master')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Détail d'étudiant</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Accueil</a></li>
              <li class="breadcrumb-item active"> Profil</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="../../dist/img/user4-128x128.jpg"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ $etudiant->nom }}</h3>


                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Nom</b><a class="float-right">{{ $etudiant->prenom }}</a>
                  </li>
                  <li class="list-group-item">
                    <b>CIN</b> <a class="float-right">{{ $etudiant->cin }}</a>
                  </li>
                  <li class="list-group-item">
                    <b> Email</b> <a class="float-right">{{ $etudiant->email}}</a>
                  </li>
                  <li class="list-group-item">
                    <b> Telephone</b> <a class="float-right">{{ $etudiant->tel}}</a>
                  </li>
                  <li class="list-group-item">
                    <b> Adresse</b> <a class="float-right">{{ $etudiant->adresse}}</a>
                  </li>
                  <li class="list-group-item">
                    <b> Nationnalité</b> <a class="float-right">{{ $etudiant->nationalite}}</a>
                  </li>
                
                  
                </ul>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->

            <!-- /.card -->
          </div>
          <!-- /.col -->
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection